apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ssh-notify
  labels:
    tier: monitoring
    app: ssh-notify
    version: v1
spec:
  template:
    metadata:
      labels:
        name: ssh-notify
    spec:
      # Filter to specific nodes:
      # nodeSelector:
      #  app: ssh-notify
      containers:
        - name: install
          resources:
            requests:
              cpu: 0.15
          env:
            - name: SSHNOTIFY_SLACK_WEBHOOK
              value: https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX 
            - name: SSHNOTIFY_SLACK_CHANNEL
              value: "#ssh"
            - name: SSHNOTIFY_PAM_CONFIG
              value: /etc/pam.d/system-remote-login
            - name: SSHNOTIFY_DIR
              value: /var/lib/toolbox/ssh-notify/
          image: ddub/ssh-notify 
          volumeMounts:
            - name: pam-config
              mountPath: /etc/pam.d
            - name: toolbox
              mountPath: /var/lib/toolbox/ssh-notify
      volumes:
        - name: pam-config
          hostPath:
              path: /etc/pam.d
        - name: toolbox 
          hostPath:
              path: /var/lib/toolbox/ssh-notify
